#!/bin/bash

if [[ $# != 0 ]]; then
    echo "Usage show-server"
    exit 1
fi


function get_descendents()
{
    local descendents=

    for pid in $(pgrep -P "$1"); do
        descendents="$descendents $pid"
        pid_descendents=$(get_descendents $pid)
        if [[ -n "$pid_descendents" ]]; then
            descendents="$descendents $pid_descendents"
        fi
    done

    echo $descendents
}


server=$(ps -C server -o pid= | head -n1)

if [[ -z $server ]]; then
    echo "No server process!"
    exit 1
fi

descendents=$(get_descendents $server)

echo "Server processes and threads:"
ps -L -o pid,tid,ppid,stat,comm $server $descendents
echo

for p in $server $descendents; do
    /usr/bin/lsof -a -R -d '^cwd,^txt,^mem,^rtd' -p $p
done

exit

#EOF
