brokenclients:
	gcc -Wall -DDEBUG -o client-child-sigint BrokenClients/client-child-sigint.c
	gcc -Wall -DDEBUG -o client-child-sigquit BrokenClients/client-child-sigquit.c
	gcc -Wall -DDEBUG -o client-failed-challenge BrokenClients/client-failed-challenge.c
	gcc -Wall -DDEBUG -o client-failed-port BrokenClients/client-failed-port.c
	gcc -Wall -DDEBUG -o client-failed-proceed BrokenClients/client-failed-proceed.c
	gcc -Wall -DDEBUG -o client-failed-secret BrokenClients/client-failed-secret.c
	gcc -Wall -DDEBUG -o client-parent-sigint BrokenClients/client-parent-sigint.c
	gcc -Wall -DDEBUG -o client-parent-sigquit BrokenClients/client-parent-sigquit.c
	gcc -Wall -DDEBUG -o client-wait-on-connect BrokenClients/client-wait-on-connect.c
	gcc -Wall -DDEBUG -o client-wait-on-handshake BrokenClients/client-wait-on-handshake.c
	gcc -Wall -DDEBUG -o client-no-tty-tester BrokenClients/client-no-tty-tester.c

nottyclient:
	gcc -Wall -o client-no-tty-tester BrokenClients/client-no-tty-tester.c
