#!/bin/bash

# Version 0.1
# Author: Norman Carver
# Script which will display any sockets on port 4070.
#
# Usage: show-sockets


if [[ $# != 0 ]]; then
    echo "Usage show-sockets"
    exit 1
fi

lsof -i :4070

exit

#EOF
