client:
	gcc -Wall -o client client.c

server:
	gcc -Wall -pthread -lrt -o server server.c

clientD:
	gcc -Wall -DDEBUG -o client client.c

serverD:
	gcc -Wall -pthread -lrt -DDEBUG -o server server.c