client:
	gcc -Wall -o client client.c

server:
	gcc -Wall -pthread -o server server.c -lrt

clientD:
	gcc -Wall -DDEBUG -o client client.c

serverD:
	gcc -Wall -pthread -DDEBUG  -o server server.c -lrt
